source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FlowBarButtonItem_Example', :exclusive => true do
  pod "FlowBarButtonItem", :path => "../"
end

target 'FlowBarButtonItem_Tests', :exclusive => true do
  pod "FlowBarButtonItem", :path => "../"

  
end
